#!/bin/bash
# Quick Build Script for Calm Burst Android App
# This script helps set up and build the Android app

set -e  # Exit on error

echo "=========================================="
echo "Calm Burst - Android App Build Script"
echo "=========================================="
echo ""

# Check for Java
if ! command -v java &> /dev/null; then
    echo "❌ ERROR: Java not found. Please install JDK 17 or later."
    exit 1
fi

echo "✅ Java found: $(java -version 2>&1 | head -n 1)"

# Check for Android SDK
if [ -z "$ANDROID_HOME" ] && [ -z "$ANDROID_SDK_ROOT" ]; then
    echo ""
    echo "⚠️  WARNING: Android SDK not found!"
    echo ""
    echo "Please install Android SDK and set environment variable:"
    echo "  export ANDROID_HOME=/path/to/android-sdk"
    echo ""
    echo "Or update local.properties with:"
    echo "  sdk.dir=/path/to/android-sdk"
    echo ""
    echo "Download Android SDK from:"
    echo "  https://developer.android.com/studio"
    echo ""
    exit 1
fi

echo "✅ Android SDK found: $ANDROID_HOME"

# Update local.properties
if [ ! -f "local.properties" ]; then
    echo "Creating local.properties..."
    cat > local.properties <<EOF
# Auto-generated by build.sh
sdk.dir=${ANDROID_HOME}

# AdMob Test IDs
ADMOB_APP_ID=ca-app-pub-3940256099942544~3347511713
ADMOB_BANNER_ID=ca-app-pub-3940256099942544/6300978111
EOF
fi

# Make gradlew executable
chmod +x gradlew

# Choose build type
echo ""
echo "Select build type:"
echo "  1) Debug APK (for testing)"
echo "  2) Release APK (for production - requires keystore)"
echo ""
read -p "Enter choice [1-2]: " choice

case $choice in
    1)
        echo ""
        echo "Building Debug APK..."
        ./gradlew assembleDebug

        APK_PATH="app/build/outputs/apk/debug/app-debug.apk"

        if [ -f "$APK_PATH" ]; then
            echo ""
            echo "✅ SUCCESS! Debug APK built successfully!"
            echo ""
            echo "APK Location: $APK_PATH"
            echo "File size: $(du -h $APK_PATH | cut -f1)"
            echo ""
            echo "To install on connected device:"
            echo "  adb install $APK_PATH"
            echo ""
        else
            echo "❌ Build failed - APK not found"
            exit 1
        fi
        ;;
    2)
        echo ""
        echo "Building Release APK..."
        echo ""
        echo "⚠️  NOTE: Release builds require a signing keystore."
        echo "See BUILD_AND_DEPLOY.md for keystore setup instructions."
        echo ""

        ./gradlew assembleRelease

        APK_PATH="app/build/outputs/apk/release/app-release.apk"

        if [ -f "$APK_PATH" ]; then
            echo ""
            echo "✅ SUCCESS! Release APK built successfully!"
            echo ""
            echo "APK Location: $APK_PATH"
            echo "File size: $(du -h $APK_PATH | cut -f1)"
            echo ""
        else
            echo "❌ Build failed - APK not found"
            exit 1
        fi
        ;;
    *)
        echo "Invalid choice. Exiting."
        exit 1
        ;;
esac

echo ""
echo "=========================================="
echo "Build complete!"
echo "=========================================="
